# Generated by Django 6.0.5 on 2026-06-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amir', '0002_post_created_at_post_email_post_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imaje',
            field=models.ImageField(default='amir/default.jpg', upload_to='amir/'),
        ),
    ]
