# Generated by Django 6.0.5 on 2026-06-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amir', '0003_post_imaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='amir.category'),
        ),
    ]
