# Generated by Django 6.0.5 on 2026-07-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amir', '0007_contact_alter_category_options_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
